# Generated by Django 4.1.5 on 2023-01-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=30)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
