# Generated by Django 4.1.5 on 2023-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=30)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('comment_article_id', models.IntegerField()),
            ],
        ),
    ]
