# Generated by Django 4.1.5 on 2023-01-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_teg',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=50),
        ),
    ]
