# Generated by Django 4.1.5 on 2023-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_article_teg_alter_article_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='', upload_to='article_imgs/'),
            preserve_default=False,
        ),
    ]
